### PR TITLE
Added [Serialize] to RigidTransform.

### PR DESCRIPTION
**Pull request by unpacklo**
A request from @seant-unity

### CODE REVIEW

**Comment by xoofx** [comment]
As this is a breaking change for a verified package, you need to add `UNITY_2020_1_OR_NEWER` to the serializable field

**Comment by xoofx** [comment]
Actually, it seems to be tagged as a breaking change... that would require us to bump the major version of mathematics and to have to maintain 2 version... 
We need to investigate why validation is reporting this and if we have any possible workaround

**Comment by unpacklo** [comment]
How can I run this validation test suite?

**Comment by xoofx** [comment]
> How can I run this validation test suite?

@fabriziounity

**Comment by fabriziounity** [comment]
After you clone
1) cd Unity.Mathematics
2) npm install upm-ci-utils@stable --registry https://api.bintray.com/npm/unity/unity-npm -g
3) upm-ci package pack --package-path src/
4) upm-ci package test --package-path src/ --unity-version 2018.4    (or whatever editor you want to try, `trunk` will work too....it needs to pass validation for all editors 2018.4+)

**Comment by fabriziounity** [comment]
FYI, master branch is now validating against all the editor versions we support. If you merge master in this branch, any change will go through all the editors (which might be more convenient than running locally for all the editors probably).

**Comment by unpacklo** [comment]
I finally got around to asking about this validation error and it seems like adding `[Serializable]` should not be considered an error (according some folks in #devs-packman).  This doesn't seem like something I can fix at the moment, so maybe I should just close this PR for now?

**Pull request closed without merging**
