### PR TITLE
Affine transform

### PR DESCRIPTION
**Pull request by oldio**
Adding affine transform type

### CODE REVIEW

**Review by mecanimdev — APPROVED** [review]
nice works guys

**Comment by unpacklo** [comment]
@oldio is there a .csproj file update for the Unity.Mathematics solution?

When I try to build and run the Burst tests (in their repo), it complains that it can't find `AffineTransform` and I suspect it's because the solution doesn't know about the new file.

**Comment by oldio** [comment]
> @oldio is there a .csproj file update for the Unity.Mathematics solution?

Fixed in https://github.com/Unity-Technologies/Unity.Mathematics/pull/212/commits/84a8c6aad160980dd26846ed42faa72722769f36

**Comment by unpacklo** [comment]
@jo-unity could you give this a documentation review?

**Review by jo-unity — APPROVED** [review]
Looks good to me - this seems like a really useful api addition - I wonder if this could be a potential one to add to the list for writing some supporting user manual content for @unpacklo ? might be useful to get some more detailed examples / workflows of where you would want to use this in a real game :)

**Comment by unpacklo** [comment]
> Looks good to me - this seems like a really useful api addition - I wonder if this could be a potential one to add to the list for writing some supporting user manual content for @unpacklo ? might be useful to get some more detailed examples / workflows of where you would want to use this in a real game :)

Yes, for sure! I'm working on making some more types in Unity.Mathematics public so they can actually be used and one thing I'm doing is making small samples to illustrate their use. I'm planning on doing something similar for the recent PRs we've had for the singular value decomposition and the new code in this PR.

**Review by unpacklo — APPROVED** [review]

**Pull request merged**
