### PR TITLE
Fix burst compile failures.

### PR DESCRIPTION
**Pull request by unpacklo**
Recent commits made use of various asserts which are not supported by burst.  Modified code to use the supported asserts.

### CODE REVIEW

**Comment by unpacklo** [comment]
Running tests in burst without this commit:

image

Running tests in burst with this commit:

image

**Comment by tgjones-unity3d** [comment]
I've added `Assert.AreNotEqual` support to Burst.

**Comment by unpacklo** [comment]
> I've added `Assert.AreNotEqual` support to Burst.

Will it be safe for me to use this assert future versions of Unity.Mathematics?  I'm concerned that because burst depends on mathematics (and not the other way around) that there won't be a way for me to guarantee that assert will be available in burst compiled code.

**Comment by tgjones-unity3d** [comment]
>> I've added Assert.AreNotEqual support to Burst.

> Will it be safe for me to use this assert in future versions of Unity.Mathematics?

I was thinking about that. I think the answer is "yes, it's safe", because:

* You're only using these asserts in Unity.Mathematics tests, not non-test Burst-able code.
* When you run these tests as part of the Unity.Mathematics package inside Unity, they will use Unity's normal test runner and work fine.
* The Burst package on the Unity.Mathematics package, but the Burst package doesn't itself include tests from the Unity.Mathematics package.

Does that sound right @xoofx?

**Pull request merged**
